# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
parameters:
    brands_dev_allowed_suffixes: []
    brands_default: 'default'
    brands_map:
        # hostname: brand_key
        # Map production and local hostnames to their brand
        # 'dashboard.example.com': 'default'
        # 'dashboard.example.local': 'default'
        # 'dark.example.com': 'jarvis'
        # 'dark.example.local': 'jarvis'
        # 'topnav.example.com': 'topnav'
    brands_defs:
        default:
            name: 'Default'
            menu: sidebar
            dark: false
        topnav:
            name: 'Top Nav'
            menu: topnav
            dark: false
        jarvis:
            name: 'Jarvis'
            menu: sidebar
            dark: true
        watson:
            name: 'Watson'
            menu: topnav
            dark: true
